prepare:
  target_col: "Survived"
  test_size: 0.2
  random_state: 42
  drop_columns: ["PassengerId", "Name", "Ticket", "Cabin"]
  cat_cols: ["Sex", "Embarked"]

model:
  name: "LogisticRegression"
  C: 1.0
  max_iter: 200

mlflow:
  host: "http://127.0.0.1:5000"
